src/services/context/index.ts, src/services/context/type.ts, src/utils/announcementFormat.ts, src/views/Announcement/Announcement.vue, src/views/Announcement/AnnouncementDetail.vue, src/views/Announcement/announcementFormat.ts, src/views/Home.vue
=> Announcement

src/composition/biz/useInitRequest.ts, src/router/index.ts, src/services/book/types.ts, src/views/Announcement/AnnouncementDetail.vue, src/views/Book/BookInfo.vue, src/views/Home.vue, src/views/Read.vue
=> 实现前进刷新后退不刷新

src/plugins/icon/export.ts, src/views/Announcement/Announcement.vue
=> 在公告列表框 靠右放置刷新按钮

src/services/book/index.ts, src/services/user/index.ts, src/views/History.vue
=> historyPage

src/plugins/icon/export.ts, src/plugins/quasar/options.ts, src/views/Read.vue
close #45 
问一点小问题
1. 部署在本地主机后后手机局域网访问，登陆时会报错`hash.ts`文件中的`crypto.subtle`为`undefined`，原因是非https远程访问不支持`crypto.subtle`。因此无法简单地进行本地移动端调试，请问有什么办法解决吗？
2. 我没怎么用过github协同开发，所以有点不太熟悉开发流程。请问pull request的时候应该merge到master分支还是某个dev分支上？
=> feat(Read.vue): 添加全屏切换按钮

src/store/setting.ts, src/views/Read.vue, src/views/Setting.vue
=> feat(Read.vue): 点击屏幕边缘滚动页面

src/store/shelf.ts
close https://github.com/LightNovelShelf/Web/issues/54
=> fix: 修正useShelfStore被多次调用的情况下会触发多次初始化请求的问题

src/components/app/Header.vue, src/components/app/useLayout.ts, src/views/MyShelf/List.vue
store一般用来面向跟重量的操作，比如包含对store的操作(action)也需要抽象时; 简单场景下可简化为使用ref；
且对store的state直接修改感觉怪怪的，一般提倡单项数据
=> feat: 采用ui框架内置变量代替dynaicHeaderHeight；简化useLayout实现

src/services/internal/request/createRequestQueue.ts, src/services/internal/request/fetch.ts, src/services/internal/request/signalr/index.ts, src/services/user/index.ts, src/utils/rateLimitQueue.ts
close #58 
目前实现是一个请求类型一个队列，互相之间单独计数互不干涉；
要换成一起计数也不难，但目前觉得分开比较符合目标就这样实现了
=> 实现全局请求速率限制

src/components/HtmlEditor.vue
=> fix(HtmlEditor.vue): 修正md注音错误

src/views/Book/Read.vue, src/views/User/Profile.vue
=> fix profile background

src/components/app/Container/index.vue, src/components/app/useLayout.ts, src/plugins/quasar/dark.ts, src/store/setting.ts, src/views/Search.vue, src/views/Setting.vue
=> improve page width

src/views/Book/BookInfo.vue
=> bookinfo scroll

src/views/Book/Read.vue
=> fix read page style

src/views/Book/Read.vue
接管read頁面a標籤點擊
1. 點擊事件監聽掛在body上
2. a標籤href可為
1. https://github.com
2. //github.com
3. github.com
4. https://www.lightnovel.app/read/1508/2
5. //www.lightnovel.app/read/1508/2
6. www.lightnovel.app/read/1508/2
7. /read/1508/2
3. a標籤href不可為
1. Github.com
2. read/1508/2
4. 同源網址會使用router.push，其他網站使用window.open
https://www.lightnovel.app/read/1508/2
目前沒找到其他種類的連結可以測試a標籤點擊行為
=> feat: 接管read頁面a標籤點擊 #114

src/views/User/BookEditor.vue, src/views/User/Publish.vue
=> 修复页面空缺与保存判断逻辑

src/components/app/Side.vue, tsconfig.json
跳过解析 node_modules，不添加这个 vscode 会报 node_modules 里的 error
修一下 route.name 的类型
=> 临时修复 当前在线 位置，并修复一些小问题

src/composition/useToNowRef.ts, src/utils/time.ts
close [189](https://github.com/LightNovelShelf/Web/issues/189)
=> 修正时间格式化会出现未来时间文案的问题

src/views/User/Publish.vue
=> fix(User): sync categoryOptions with server

src/views/Login/Login.vue, src/views/Login/VueTurnstile.vue
使得登录按钮在 turnstile 未通过前不可点击，解决手快按钮需要点两次的问题。
使得 turnstile 组件语言为ts
=> feat: 优化登录按钮

.npmrc, .vscode/settings.json, eslint.config.js, src/App.vue, src/components/SearchInput.vue, src/components/app/Header.vue, src/components/html/Editor/MarkDown.vue, src/composition/useToNowRef.ts, src/pages/Announcement/Announcement.vue, src/pages/History.vue, src/pages/Login/Login.vue, src/pages/MyShelf/components/NavBackToParentFolder.vue, src/services/internal/request/signalr/inspector.ts, src/stores/app.ts, src/utils/useForwardRef.ts, tsconfig.json
[fix: 修正输入框在空输入开始输入时无法打开menu的问题](https://github.com/LightNovelShelf/Web/pull/208/commits/60faa61358605603f84b4256d991d371efd3f02b)
[fix: 修正在搜索框输入回车时会跳转焦点至分页器的问题](https://github.com/LightNovelShelf/Web/pull/208/commits/dff4db7599c461f0358a3dfd5ea4ec4030fa04a5)
=> feat: 顶部搜索框体验优化

src/components/app/Header.vue, src/pages/Search.vue, src/router/routes.ts
其实并不是keey-alive 的问题，而是搜索结果页自身每每watch到url变化都初始化一次
close #213
=> 搜索结果页支持返回保持

src/pages/Search.vue
原因是route reuse了这个组件，mounted和actived都没触发
=> fix: 修正搜索页不会响应header搜索框的问题
